package migrations

import (
	"github.com/pocketbase/pocketbase/core"
)

// Add PostgreSQL functions table
func init() {
	core.SystemMigrations.Register(func(txApp core.App) error {
		db := txApp.DB()

		_, err := db.NewQuery(`
			CREATE TABLE IF NOT EXISTS "_pg_functions" (
				"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				"uuid" uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
				"created" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
				"updated" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
				"name" varchar(63) NOT NULL,
				"schema" varchar(63) NOT NULL DEFAULT 'public',
				"body" text NOT NULL,
				"parameters" jsonb NOT NULL DEFAULT '[]',
				"return_type" varchar(255) NOT NULL,
				"language" varchar(32) NOT NULL DEFAULT 'plpgsql',
				"volatility" varchar(16) NOT NULL DEFAULT 'VOLATILE',
				"security" varchar(16) NOT NULL DEFAULT 'INVOKER',
				"description" text NOT NULL DEFAULT '',
				"is_active" boolean NOT NULL DEFAULT true
			);

			CREATE UNIQUE INDEX IF NOT EXISTS "_pg_functions_name_schema_idx" ON "_pg_functions" ("name", "schema");
			CREATE INDEX IF NOT EXISTS "_pg_functions_created_idx" ON "_pg_functions" ("created");
			CREATE INDEX IF NOT EXISTS "_pg_functions_is_active_idx" ON "_pg_functions" ("is_active");
		`).Execute()

		return err
	}, func(txApp core.App) error {
		db := txApp.DB()
		_, err := db.NewQuery(`DROP TABLE IF EXISTS "_pg_functions"`).Execute()
		return err
	}, "1737052400_add_pg_functions.go")
}
